### ISSUE TITLE
App doesn't start when I change something in the code

### ISSUE THREAD

**Issue by nubbel** [lechium/HelloWorld_ATVBlack#1]
Hi, thanks for your HelloWorld project!

I'd like to use it as a starting point for my own ATV 2 project. However if I change something in the code, it doesn't matter what, the app won't start anymore.

I think it has something to do with the file size, because when I remove a letter from a string and add a letter to another, it perfectly works.

It would be awesome, if you could help me with that. I don't have any idea how the RunScript.sh or the package-v.sh work, but the error has to be there, right?

Greets!

**Comment by lechium** [comment]
the size has no bearing on anything, what are you trying to change or add? i need more concrete examples for me to be able to help you.

**Comment by nubbel** [comment]
Ok, I was wrong. Sorry.

How ever, I need to build and run twice. The second time it works.
Is there a way to build only once?

How did you learned ATV 2 programming? Are there any resources except the private header files?

**Comment by lechium** [comment]
i've been doing this since the first appletv came out, there was a very vibrant community (that is still slightly intact, but not nearly as active) on irc server irc.moofspeak.net room #awkwardtv that is where i did a LOT of my learning. but yes a lot of it is still done through header files / trial and error, and poking around with cycript.
